version: "2.2"
services:
  jobmanager:
    build: ./
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager 
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=key
    volumes:
      - ./data:/tmp/hudi/
      - /hive-site.xml:/opt/flink/hive/hive-site.xml

      
  taskmanager:
    build: ./
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20  
      - ./data:/tmp/hudi
      - /hive-site.xml:/opt/flink/hive/hive-site.xml
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=key


  sql-client:
    build: ./
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager  
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=key
    volumes:
      - ./data:/tmp/hudi
      - ./hive-site.xml:/opt/flink/hive/hive-site.xml

     